# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Grigoprint
email: info@bandieregrigolini.it
description: >- # this means to ignore newlines until "baseurl:"
  Grigolini di Illasi, Verona, si occupa della
  stampa digitale su tessuto in poliestere, quali bandiere personalizzate, ombrelloni,
  poster, striscioni in TNT e molto altro.
logo: /assets/images/logo.svg
baseurl: '' # the subpath of your site, e.g. /blog
url: 'https://www.grigoprint.it' # the base hostname & protocol for your site, e.g. http://example.com
# url: 'http://127.0.0.1'
twitter_username: grigoprint
# github_username:  jekyll
google_analytics: UA-139665476-1
# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-responsive-image
  - jekyll-sitemap
  - jekyll/minibundle
  - jekyll-paginate
  - jekyll-archives
  #- jekyll-compass
sass:
  style: compressed
  sass_dir: _sass
  load_paths:
    - '/home/puce/Documents/grigoweb/grigoprint/node_modules/susy/sass'
  #  - "/home/puce/.rvm/gems/ruby-2.5.1/gems/compass-core-1.0.3/stylesheets/"
lang: it
compress_html:
  clippings: all
  comments: ['<!--', '-->']
  startings: [html, body]
  endings:
    [
      html,
      body,
      li,
      dt,
      dd,
      rt,
      rp,
      optgroup,
      option,
      colgroup,
      caption,
      thead,
      tbody,
      tfoot,
      tr,
      td,
      th
    ]
  profile: false
  blanklines: false
  ignore:
    envs: []
# minifying js
minibundle:
  minifier_commands:
    js: node_modules/.bin/uglifyjs

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
exclude:
  [
    node_modules/*.*,
    _kits/*.html,
    landing/*.html,
    _prodotti/canotte-personalizzate.html,
    _prodotti/coperture-gazebo.html,
    _prodotti/gazebo.html,
    _prodotti/roll-up.html,
    _prodotti/spille.html,
    email/*.*,
    blog/*.*,
    tessuti.html
  ]
defaults:
  - scope:
      path: '_kits/*.html'
    values:
      sitemap: false
  - scope:
      path: 'landing/*.html'
    values:
      sitemap: false
  - scope:
      path: 'node_modules/*.*'
    values:
      sitemap: false

collections:
  prodotti:
    output: true
  kits:
    output: true

responsive_image:
  # [Required]
  # Path to the image template.
  template: _includes/responsive-image.html

  # [Optional, Default: 85]
  # Quality to use when resizing images.
  default_quality: 90

  # [Optional, Default: []]
  # An array of resize configuration objects. Each object must contain at least
  # a `width` value.
  sizes:
    - width: 480 # [Required] How wide the resized image will be.
      quality: 80 # [Optional] Overrides default_quality for this size.
    - width: 800
    - width: 1400
      quality: 90

  # [Optional, Default: false]
  # Rotate resized images depending on their EXIF rotation attribute. Useful for
  # working with JPGs directly from digital cameras and smartphones
  auto_rotate: false

  # [Optional, Default: false]
  # Strip EXIF and other JPEG profiles. Helps to minimize JPEG size and win friends
  # at Google PageSpeed.
  strip: false

  # [Optional, Default: assets]
  # The base directory where assets are stored. This is used to determine the
  # `dirname` value in `output_path_format` below.
  base_path: assets

  # [Optional, Default: assets/resized/%{filename}-%{width}x%{height}.%{extension}]
  # The template used when generating filenames for resized images. Must be a
  # relative path.
  #
  # Parameters available are:
  #   %{dirname}     Directory of the file relative to `base_path` (assets/sub/dir/some-file.jpg => sub/dir)
  #   %{basename}    Basename of the file (assets/some-file.jpg => some-file.jpg)
  #   %{filename}    Basename without the extension (assets/some-file.jpg => some-file)
  #   %{extension}   Extension of the file (assets/some-file.jpg => jpg)
  #   %{width}       Width of the resized image
  #   %{height}      Height of the resized image
  #
  output_path_format: assets/resized/%{width}/%{dirname}/%{basename}

  # [Optional, Default: true]
  # Whether or not to save the generated assets into the source folder.
  save_to_source: false

  # [Optional, Default: false]
  # Cache the result of {% responsive_image %} and {% responsive_image_block %}
  # tags. See the "Caching" section of the README for more information.
  cache: false

  # [Optional, Default: []]
  # By default, only images referenced by the responsive_image and responsive_image_block
  # tags are resized. Here you can set a list of paths or path globs to resize other
  # images. This is useful for resizing images which will be referenced from stylesheets.
  extra_images:
    - assets/foo/bar.png
    - assets/bgs/*.png
    - assets/avatars/*.{jpeg,jpg}

cloudinary:
  cloud_name: dum2puxhq
  only_prod: true
  verbose: true
  origin_url: https://www.grigoprint.it
  presets:
    default:
      min_width: 320
      max_width: 1600
      fallback_max_width: 800
      steps: 5
      sizes: '(min-width: 50rem) 50rem, 90vw'
      attributes:
        class: 'lazyload'
    jumbotron:
      min_width: 320
      max_width: 2500
      fallback_max_width: 1200
      steps: 5
      sizes: '(min-width: 320px) 100vw'
      attributes:
        class: 'lazyload'
    halfscreen:
      min_width: 320
      max_width: 1200
      fallback_max_width: 1000
      steps: 5
      sizes: '(min-width: 320px) 100vw, (min-width: 992px) 50vw'
      attributes:
        class: 'lazyload'
    onethird:
      min_width: 250
      max_width: 535
      fallback_max_width: 300
      steps: 5
      sizes: '(min-width: 50rem) 17rem, 30vw'
      attributes:
        class: 'lazyload'
    onequater:
      min_width: 250
      max_width: 600
      fallback_max_width: 300
      steps: 5
      sizes: '(min-width: 50rem) 50rem, 50vw'
      attributes:
        class: 'lazyload'
    thumbnail:
      min_width: 135
      max_width: 400
      fallback_max_width: 300
      steps: 3
      sizes: '(min-width: 320px) 40vw, (min-width: 768px) 25vw'
      attributes:
        class: 'lazyload'
#Pagination
paginate: 5
paginate_path: '/blog/page:num/'

picture:
    source: "assets/images/fullsize"
    output: "assets/images/generated"
    relative_url: false
    suppress_warnings: true
